### ISSUE TITLE
how to get GL Arab source to certin channel

### ISSUE THREAD

**Issue by ramboo80** [allouch89/ShaniXBMCdatabase#96]
Hi Shani
I have this channel 
<cname>Al Nahar Cinema</cname>
	<imageurl>http://i1376.photobucket.com/albums/ah34/ramboo80/Al%20Nahar%20Cinema_zpsfb8aqbks.png?t=1494533850</imageurl>
	<enabled>True</enabled>
	<assignedcategory>
	<category>egypt</category>
	</assignedcategory>
	
it has only teledunet as a source and not working ...how to get GL Arab source to this channel?
Am still confused about GL Aarab because it has no Urlfile here how do we make changes on channels that has GL Arab source?

**Comment by emadmahdi** [comment]
GLArab does not provide all channels ... so are you sure that "Al-Nahar Cinema" exist in GLArab ?!!!

**Comment by ramboo80** [comment]
Yes am sure because I used to play the channel with GL Arab source and it was not down untill i made a change..but the thing is Al Nahar Cinema chan stream  had a wrong chan logo and name wich was ( Al Nahar +2) logo and name was (Al Nahar 2) so i tried to correct that and changed chan logo and name to Al Nahar Cinema..now after change i sow 2 Al Nahar Cinema channels one with logo and the other without logo and both has only teledunet as a source..Shani said after i changed chan name that i must check when changing channel name that the new name does not exist in other url files..and i checked and it was there under teledunet url file..so i think that made everything wrong.

**Comment by emadmahdi** [comment]
@Shani-08 ... Will you please change the channel name in file "glarabUrls.xml" ... line 7959 and line 5747 ... both shoudl read "Al Nahar Cinema" instead of "Al Nahar 2" ... i have no access to glarab file ...

@ramboo80 ... For the duplicated channel name ... I deleted the extra channel ... and I also added the new channel "Al Nahar 2" ...

**Comment by ramboo80** [comment]
Yes thanks emadmahdi the channel is back now Al Nahar 2 the name.. with no logo  and the stream is Al Nahar Cinema ..waiting for Shani to change the name so all we be good...are you from Iraq?..am Abo Hassan from Iraq thanks for the help and nice to meet you.

**Comment by ramboo80** [comment]
by the way  i can't see the GL Arab url file...I know that we dont have accses to that file but most of the channels we have today are working with that source GL Aarab and there are some channels have been updated so the logos does not match the stream or the name does not match..It will be good if we could make updates to those channels by accessing that file.

**Comment by emadmahdi** [comment]
@ramboo80 ...

glaraburl.xml file is maintained by @Shani-08 using offshoregit.com storage ...

We put lots of efforts to make this glarab works without problems and it is important to keep it secure as much as possible ... so i do support shani in separating this file from the rest of the shahid addon files ...

I was the first person introduced glarab to shani but since then lots of changes happened and that was a good reason to make this source secure especially after the issue of copyright and geoblock that also forced shani to separate this file from the rest of the development ...

**Comment by ramboo80** [comment]
Oh OK i see then i totally agree with you guys by keeping it secure.

**Comment by Shani-08** [comment]
More than keeping it secure, the Issue was the DMCA so its been removed, if you have to make changes, send me the new xml file.

**Comment by emadmahdi** [comment]
@Shani-08 ... Will you please change the channel name in file "glarabUrls.xml" ... line 7959 and line 5747 ... both should read "Al Nahar Cinema" instead of "Al Nahar 2" ... Thanks

**Comment by Shani-08** [comment]
done, next time you can make changes to the file, upload to pastebin and link here
